auth-server: http://localhost:8420/auth # 认证服务器地址

server:
  port: 8826
security:
  oauth2:
    client:
      client-id: client # 授权服务器配置的client id
      client-secret: secret # 授权服务器配置的client secret
      scope: all
      #access-token-uri: ${auth-server}/oauth/token # 获取access token接口
      #user-authorization-uri: ${auth-server}/oauth/authorize #  获取Authorization Code接口
    resource:
      token-info-uri: ${auth-server}/oauth/check_token # 验证token的接口
      id: client
#      user-info-uri: ${auth-server}/user # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
#      prefer-token-info: true # 如果同时配置了token-info-uri 和 user-info-uri，这个现象设置使用哪个取验证授权

mybatis:
  type-aliases-package: com.govmaz.entity
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.146.44:3306/pwourk_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin@911
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss