server:
  servlet:
    context-path: /auth
  port: 8420

spring:
  datasource:
    url: jdbc:mysql://47.103.146.44:3306/oauth_center?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin@911
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 47.103.146.44
    password: redis@911
    timeout: 8000
    port: 6379
jasypt:
  encryptor:
    password: abc123