auth-server: http://localhost:8420/auth # 认证服务器地址

server:
  port: 8812
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: all
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
mybatis:
  type-aliases-package: com.govmaz.entity
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.146.44:3306/pwourk_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin@911
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss